Revert "Removes NCR MP + Sergeant MP loadout" and gives them razors
AtomBombf13/AtomBomb pull request #256
Opened 2022-12-02 03:24 UTC by companoo

someone got salty MP's were enforcing uniform regulations

+ adds razors there loadouts
+ makes MP's corporals and removes reference to the SEA in there desc

2022-12-02 03:56 UTC, ErwinSnowden commented
speedmerge

2022-12-02 05:25 UTC, HanSolo1519 commented
sneedmerge

2022-12-02 15:44 UTC, BadAtThisGame302 commented
_**speedmerge**_

2022-12-02 16:28 UTC, RonBag requested changes

2022-12-02 16:28 UTC, RonBag commented on code/modules/jobs/job_types/ncr.dm
> +	total_positions = 1
Undocumented change.

2022-12-02 22:20 UTC, companoo commented
shouild be fixed

2022-12-02 23:42 UTC, RonBag approved these changes
The razor is a little memey, but looks good

2022-12-02 23:52 UTC, BadAtThisGame302 commented on code/modules/jobs/job_types/ncr.dm
> +	description = "Your enlisted with a medical skill set. You work closely with your squad, taking orders from your officers. You have the authority to command troopers if there are no non-commissioned
You're an*

2022-12-03 00:00 UTC, companoo commented on code/modules/jobs/job_types/ncr.dm
> +	description = "Your enlisted with a medical skill set. You work closely with your squad, taking orders from your officers. You have the authority to command troopers if there are no non-commissioned
whoops thank

2022-12-03 19:55 UTC, Sinbest commented
speedmerge

2022-12-03 22:53 UTC, merged