Crafting Changes
AtomBombf13/AtomBomb pull request #351
Opened 2022-12-18 06:11 UTC by BobNewman-max

## About The Pull Request
Major crafting changes, if I fucked it up. Let me know.

Shifts crafting in the BoS to the scribes to give them more reason to exist. Knights no longer get round-start books 3/4 knowledge. 

SKs can no longer craft M1 Carbines, I've been told they're good (Even though I know they're not) so they get hunting shotguns instead. 

HS gets a box which has 2 crafting recipes which are decent. They're a decent (ish) listing. They also have a chance to get an AER9/AEP7 blueprint which are there to be throw-away BPs. If they get them they're honestly gonna be useless but that's the point. They have a chance to get shit that is shit.

Fixed the codex that's in-game. Not going to add the link in there as it starts now round-start on their screen. When anyone in the BoS joins it gives them the link to the servers codex in their chat. Because no one else could be bothered to do it.

The codex in-game change is done due to the players for some reason refusing to check discord at times and also (same people) screaming at me for the in-game one being bad. On the discord. Funny.

All-in-all its done to shift crafting towards scribes rather then knights.

Paladin also gets their power-fist because Imma be real, 2 melee is stupid. Especially since the hammer is much better for damage. So why not just let them keep the good stuff. (I'll add something in the future if it seems like a pointless loadout.)

Fixed a comment that I put incorrectly about the SP getting an AER14. They're supposed to have an AER12. 

Back to the crafting changes, 

Scribes and Senior Scribes get GnB PT.1-4 learned. Because they craft stuff now.
HS gets a box of rando BPs (2) and SS can choose it as a loadout. SS also lose their 6 research blueprints and now have 3. Might reduce it further we'll see.

Knights also  get an engineer loadout. So. Fun. 

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

2022-12-18 09:08 UTC, ErwinSnowden commented
This doesn't work as intended and the "Knight-Engineer" loadout just serves to invalidate the change you made to "take G&B part 3/4 from knights", making this a direct buff.

![image](https://user-images.githubusercontent.com/46099003/208289623-c61f5f41-5e7a-4a6c-b25c-1f2d4e1c93e5.png)
Ah yes, roundstart RCW/riot shotgun blueprints... something you can only get in two of the hardest bunkers. The LSW and R84 blueprints which are both LMGs, VERY balanced. And... the infiltrator... which is a unique? Infinite uniques. Cool.

Not to mention that you also gave the senior knight the ability to craft the hunting shotgun over the M1 carbine, yet another inarguable buff since the M1 carbine shoots ten millimeter.

Beyond the fact that this doesn't work because you don't understand the GLOBAL_INIT_LIST, **hard no**. The Brotherhood already had a massive buff.

2022-12-18 10:24 UTC, BadAtThisGame302 commented
If your previous PR of adding another paladin wasn't powercreep... then this PR definitely IS powercreep.

2022-12-18 10:29 UTC, BobNewman-max commented
the box that gives them half decent weapons to craft with only 2 good guns is a power-creep, okay. Homie only the RCW is cursed, that and the R84 are powerful. But yeah I can remove the two OP ones B)

2022-12-18 10:56 UTC, ErwinSnowden commented
The infiltrator apparently uses "SEMI_AUTO_NODELAY", the only obtainable gun outside of a toy/the bow (singleshot) which does so.

It's basically on par with the sequoia and a unique handed only to the NCR lieutenant, you _can_ get it from the unique lootdrops though. I see no issue with giving it to potentially every Brotherhood member.

2022-12-18 11:12 UTC, BobNewman-max commented
> 

didn't notice, yeah I'll change that B)

2022-12-20 19:07 UTC, OliOliOnsiPree requested changes
There you go.

2022-12-20 19:07 UTC, OliOliOnsiPree commented on code/modules/jobs/job_types/bos.dm
> +	ADD_TRAIT(H, TRAIT_GUNSMITH_FOUR, src)
for(var/datum/crafting_recipe/recipe as() in GLOB.knight_gunsmith_recipes)
		H.mind.teach_crafting_recipe(recipe)

(Thats how they get the recipes via one to four)

2022-12-20 19:07 UTC, OliOliOnsiPree commented on code/modules/jobs/job_types/bos.dm
> +	ADD_TRAIT(H, TRAIT_GUNSMITH_FOUR, src)
for(var/datum/crafting_recipe/recipe as() in GLOB.knight_gunsmith_recipes)
		H.mind.teach_crafting_recipe(recipe)

2022-12-20 19:07 UTC, OliOliOnsiPree commented on code/modules/jobs/job_types/bos.dm
> +		/obj/item/storage/box/bos = 1
if you plan on giving the box to head scribe you might aswell give them the recipes that 1 - 4 get, but thats majority up to you. 

	for(var/datum/crafting_recipe/recipe as() in GLOB.knight_gunsmith_recipes)
		H.mind.teach_crafting_recipe(recipe)

2022-12-21 00:22 UTC, ErwinSnowden commented
This still doesn't work because knights don't lose their 3/4 knowledge, because they don't have separate recipe lists. 💀

2022-12-21 04:11 UTC, Legate-Maxson commented
Do to community reaction this will be closed for now.

2022-12-21 04:11 UTC, closed without merging